### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by Pierstoval** [obiwankennedy/GameVisualisationHelper#1]
The repo name is `GameVisulisationHelper`

Shouldn't it be `GameVisualisationHelper`?

😸

**Comment by obiwankennedy** [comment]
Sure,  i create it quickly yesterday

**Comment by obiwankennedy** [comment]
Fixed ! 
This is the article why i create this repo: 
http://linuxfr.org/users/obiwankennedy/journaux/mettre-ses-parties-en-ligne
